### ISSUE TITLE
pidgin: text is garbled?

### ISSUE THREAD

**Issue by star-buck** [maui-linux/maui-releases#10]
![screenshot_20170208_144226](https://cloud.githubusercontent.com/assets/840070/22739715/1fcfd732-ee0d-11e6-9990-70123c7fb0b0.png)

**Comment by llelectronics** [comment]
It looks to me like a graphics driver issue. 
I am not able to reproduce it here on one of my laptops. (radeon,intel,nouveau) 
Maybe also bound to a specific graphics card. 
Have you checked the compositor settings and switched the opengl version or even tried xrender ? 
Does it happen on other GTK+ Apps aswell ? 
Does it happen on a specific GTK+ Theme ?
